language: node_js
node_js: stable
branchs:
  only:
  - master
cache:
  directories:
  - node_modules
before_install:
- openssl aes-256-cbc -K $encrypted_260bce340b80_key -iv $encrypted_260bce340b80_iv -in vps_rsa.enc -out ~/.ssh/vps_rsa -d
- chmod 600 ~/.ssh/vps_rsa
- eval $(ssh-agent)
- ssh-add ~/.ssh/vps_rsa
- echo -e "Host vps\n\tHostName $vps_host\n\tPort $vps_port\n\tUser git\n\tStrictHostKeyChecking no\n\tIdentityFile ~/.ssh/vps_rsa\n\tIdentitiesOnly yes" >> ~/.ssh/config
- npm install -g hexo-cli
install:
- npm install
script:
- hexo clean
- hexo generate
after_success:
- cd ./public
- git init
- git config user.name "shawnho"
- git config user.email "hi@shawnho.me"
- git add .
- git commit -m "deploy blog"
- git push --force --quiet "git@vps:blog.git" master:master
